# d=open("myfile.txt","w")
# e=open("myfile.txt","a")
f=open("myfile.txt","r+")

# d.write("\nI am living in Latur")
# d.write("\nMy Name is Sohel ansar shaikh")
# e.write("\nHarry bhai bahut acche hain")
# a=f.read()
a=f.read(20)
a=f.read(20)
print(a)
# print(f)
# f.write("\nCOCSIT COLLEGE LATUR")
y=f.seek(8)
x=f.tell()
y=f.seek(10)
print(x)
x=f.tell()
f.write("\nCOCSIT COLLEGE LATUR")

print(x)
f.close()
